# Generated by Django 5.1.1 on 2024-09-18 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Tipo de gasto')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TypeIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Tipo de ingreso')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSavingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Tipo de ingreso')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=30, verbose_name='Nombre')),
                ('second_surname', models.CharField(max_length=30, verbose_name='Nombre')),
                ('identification', models.SmallIntegerField()),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=60, verbose_name='Correo electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='SavingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Monto objetivo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('description', models.TextField(verbose_name='Descripción ahorro')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.typesavingtarget', verbose_name='Tipo de ahorro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.user', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripción ingreso')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.typeincome', verbose_name='Tipo de ingreso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.user', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripción gasto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.typebill', verbose_name='Tipo de gasto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.user', verbose_name='Usuario')),
            ],
        ),
    ]
