# Generated by Django 5.1.1 on 2024-09-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_typesavingtarget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_surname',
            field=models.CharField(max_length=30, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
    ]
